# Generated by Django 3.1.4 on 2021-01-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0004_auto_20210101_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttransaction',
            old_name='ledger',
            new_name='ledgerno',
        ),
        migrations.RenameField(
            model_name='ledgerstatement',
            old_name='ClosingBalance',
            new_name='closingBalance',
        ),
        migrations.RenameField(
            model_name='ledgerstatement',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='ledgerstatement',
            old_name='ledger',
            new_name='ledgerno',
        ),
        migrations.RenameField(
            model_name='ledgertransaction',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='ledgertransaction',
            old_name='ledger',
            new_name='ledgerno',
        ),
    ]
