# Generated by Django 3.1.4 on 2021-01-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0005_auto_20210106_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountstatement',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='ledgerstatement',
            options={'get_latest_by': 'created'},
        ),
        migrations.RenameField(
            model_name='accountstatement',
            old_name='date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='ledgerstatement',
            name='created',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
