# Generated by Django 3.1.4 on 2021-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0006_auto_20210109_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ledgerstatement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
